spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

